### ISSUE TITLE
"Rate too high" But Recognation shows correct numbers

### ISSUE THREAD

**Issue by pos-ei-don** [jomjol/AI-on-the-edge-device#2903]
### The Problem

Rate too high - Read: 836.3719 - Pre: 835.3213 - Rate: 1.0506

But on the Screenshot you see that it korrect sees 835, not 836.  Why does the new read or any logic change it to 836?

### Version

v15.5.0

### Logfile

```shell
[0d00h00m05s] 2024-02-14T12:41:08 <INF> [MAIN] Reset reason: Via esp_restart
[0d00h00m05s] 2024-02-14T12:41:08 <INF> [WLANINI] SSID: 0816
[0d00h00m05s] 2024-02-14T12:41:08 <INF> [WLANINI] Password: XXXXXXXX
[0d00h00m05s] 2024-02-14T12:41:08 <INF> [WLANINI] Hostname: watermeter
[0d00h00m05s] 2024-02-14T12:41:08 <INF> [WLANINI] RSSIThreshold: -80
[0d00h00m05s] 2024-02-14T12:41:08 <INF> [MAIN] WLAN config loaded, init WIFI...
[0d00h00m05s] 2024-02-14T12:41:08 <INF> [WIFI] Automatic interface config --> Use DHCP service
[0d00h00m05s] 2024-02-14T12:41:08 <INF> [WIFI] Set hostname to: watermeter
[0d00h00m05s] 2024-02-14T12:41:08 <INF> [WIFI] Init successful
[0d00h00m07s] 2024-02-14T12:41:11 <INF> [WIFI] Connected to: 0816, RSSI: -65
[0d00h00m08s] 2024-02-14T12:41:12 <INF> [WIFI] Assigned IP: 192.168.10.43
[0d00h00m09s] 2024-02-14T12:41:12 <INF> [SNTP] Time is synced with NTP Server 192.168.10.100: 2024-02-14 12:41:12
[0d00h00m09s] 2024-02-14T12:41:12 <INF> [MAIN] Device info: CPU cores: 2, Chip revision: 100
[0d00h00m09s] 2024-02-14T12:41:12 <INF> [MAIN] SD card info: Name: SU04G, Capacity: 3781MB, Free: 3756MB
[0d00h00m11s] 2024-02-14T12:41:14 <INF> [MAIN] Initialization completed successfully
[0d00h00m13s] 2024-02-14T12:41:17 <INF> [LOGFILE] Set log level to ERROR
[0d00h00m53s] 2024-02-14T12:41:56 <ERR> [POSTPROC] main: Raw: 0835.3719, Value: , Status: Rate too high - Read: 836.3719 - Pre: 835.3213 - Rate: 1.0506
[0d00h05m52s] 2024-02-14T12:46:56 <ERR> [POSTPROC] main: Raw: 0835.3719, Value: , Status: Rate too high - Read: 836.3719 - Pre: 835.3213 - Rate: 1.0506
```

### Screenshots

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/1822533/110294d4-70f6-4d4f-be2a-773288d3c8d4)

### Additional Context

[TakeImage]
;RawImagesLocation = /log/source
WaitBeforeTakingPicture = 5
;RawImagesRetention = 15
Demo = false
Brightness = 0
Contrast = 0
Saturation = 0
LEDIntensity = 5
ImageQuality = 12
ImageSize = VGA
FixedExposure = false

[Alignment]
InitialRotate = 213.0
InitialMirror = false
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
FlipImageSize = false
/config/ref0.jpg 132 198
/config/ref1.jpg 498 110

[Digits]
Model = /config/dig-cont_0620_s3_q.tflite
CNNGoodThreshold = 0.5
;ROIImagesLocation = /log/digit
;ROIImagesRetention = 3
main.dig2 293 108 25 53 false
main.dig3 336 108 24 52 false
main.dig4 378 104 29 55 false
main.dig5 421 110 28 50 false

[Analog]
Model = /config/ana-cont_1207_s2_q.tflite
;ROIImagesLocation = /log/analog
;ROIImagesRetention = 3
main.ana4 444 262 97 97 false
main.ana3 359 349 97 97 false
main.ana2 241 345 96 99 false
main.ana1 157 260 97 97 false

[PostProcessing]
main.DecimalShift = 0
;main.AnalogDigitalTransitionStart = 9.7
PreValueUse = true
PreValueAgeStartup = 720
main.AllowNegativeRates = false
main.MaxRateValue = 0.8
;main.MaxRateType = AbsoluteChange
main.ExtendedResolution = false
main.IgnoreLeadingNaN = false
ErrorMessage = true
CheckDigitIncreaseConsistency = false

[MQTT]
RetainMessages = true
HomeassistantDiscovery = true
MeterType = water_m3
;CACert = undefined
;ClientCert = undefined
;ClientKey = undefined

;[InfluxDB]
;Uri = undefined
;Database = undefined
;user = undefined
;password = undefined
;main.Measurement = undefined
;main.Field = 

;[InfluxDBv2]
;Uri = undefined
;Bucket = 
;Org = undefined
;Token = undefined
;main.Measurement = undefined
main.Field = undefined

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
AutoStart = true
Interval = 5

[DataLogging]
DataLogActive = false
DataFilesRetention = 3

[Debug]
LogLevel = 1
LogfilesRetention = 3

[System]
TimeZone = CET-1CEST,M3.5.0,M10.5.0/3
;Hostname = undefined
RSSIThreshold = -80
CPUFrequency = 160
SetupMode = false

**Comment by Duese123** [comment]
Downgrade to 15.4.0 fixed this problem.

**Comment by caco3** [comment]
There was an issue in v15.5, please update to rolling where we reverted this regression.
See https://github.com/jomjol/AI-on-the-edge-device/pull/2899

**Comment by pos-ei-don** [comment]
> There was an issue in v15.5, please update to rolling where we reverted this regression. See #2899

Thank you! But "how"? I cann't find an ...update.zip, and as a none-developer, i don't know how to compile it without help.
Do i oversee an existing binary package somewhere?

**Comment by caco3** [comment]
@pos-ei-don there is no need to compile it yourself, just use the auto build as documented above

**Comment by pos-ei-don** [comment]
@caco3 Thank you, I did... but i had to find out that there is a second "Build and Pack" on this page where i can find it. 

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/1822533/0966d9f1-eb64-4db7-ba7c-3ca39c15743c)

**Comment by caco3** [comment]
> there is a second "Build and Pack" 

Ah, my bad, sry. I was unaware of this but fixed it now.

**Comment by Duese123** [comment]
You can also downgrade without Problems...

**Comment by caco3** [comment]
We just released [v15.7.0](https://github.com/jomjol/AI-on-the-edge-device/releases/tag/v15.7.0) which hopefully fixes this issue.

**Comment by pos-ei-don** [comment]
Thank you, cannot see the error in 15.7

**Comment by pos-ei-don** [comment]
Have to reopen it, it is not fixed. 
The Detection is Geräte and correct, but the results is +1 to High. 

![Screenshot_20240218-075107](https://github.com/jomjol/AI-on-the-edge-device/assets/1822533/7a30d9cb-3ce4-4b83-a2fa-c104af9ecad1)
![Screenshot_20240218-075135](https://github.com/jomjol/AI-on-the-edge-device/assets/1822533/042af671-b6ab-402a-b37d-536383343fed)

**Comment by Slider0007** [comment]
It is an early transition situation. Therefore you have to set the parameter AnalogDigitTransitionStart to a lower than the default value, e.g. 6.5. This should fix your +1 issue when digit reaches the >=x.8 region.

**Comment by Slider0007** [comment]
>;main.AnalogDigitalTransitionStart = 9.7

It is an early transition situation. Therefore you have to enable and set the parameter AnalogDigitalTransitionStart to a lower value, e.g. 6.5. This should fix your +1 issue when digit reaches the >=x.8 region.

**Comment by pos-ei-don** [comment]
Thank you, I had to Set it to 7 to work. But i did not correct lt understand the description of this value.
The Digit did not change, it was correct detected as 6.8.
I would suggest a change for the description.

**Comment by pos-ei-don** [comment]
Now, the Real  Transition is not working aswell. 9.9 gets detected as NaN, and the läßt Digit is detected as 7.  I'd love to have an Option to substract  a value like 0.2 from the last Digit unless the first analog has a transition through 0.
But maybe, this should be a separate issue. 

![Screenshot_20240218-162225](https://github.com/jomjol/AI-on-the-edge-device/assets/1822533/9d628297-b04e-45b0-adec-85054990fe65)

**Comment by Slider0007** [comment]
Please choose a ana-class100 model instead of cont-model.

**Comment by gjsiiger** [comment]
I have the exact same issue, it reads correct from the image, however result is +1.

<img width="523" alt="Screenshot 2024-02-18 at 17 16 13" src="https://github.com/jomjol/AI-on-the-edge-device/assets/118590236/0e535a7b-7f4c-4557-a401-c15ef4d3bec0">
<img width="807" alt="Screenshot 2024-02-18 at 17 15 56" src="https://github.com/jomjol/AI-on-the-edge-device/assets/118590236/221e53a8-cdb9-4a44-9ca6-9d9ed8c0f2ec">

**Comment by caco3** [comment]
@gjsiiger which version and models are you using?

**Comment by gjsiiger** [comment]
I'm on 15.7.0

[Digits]
Model = /config/dig-class100-0168_s2_q.tflite

[Analog]
Model = /config/ana-class100_0171_s1_q.tflite

**Comment by caco3** [comment]
@gjsiiger you might need to tweak the config.
see https://jomjol.github.io/AI-on-the-edge-device-docs/Watermeter-specific-analog---digital-transition/
and
https://jomjol.github.io/AI-on-the-edge-device-docs/Parameters/#parameter-numberanalogdigitaltransitionstart

**Comment by gjsiiger** [comment]
@caco3 I think I have tried every single combination (with a lot of reboots) and it doesn't seem to help.
But to be honest, I really don't understand the guide on how to calculate / set the right value 6.0 to 9.9 ?

**Comment by stephanbaron** [comment]
Same issue with 15.6.0:

Previous Value:
32.06521
Raw Value:
0032.0652
Value Status:
Rate too high - Read: 33.0652 - Pre: 32.0652 - Rate: 1.0000


Trace:

> [0d00h00m15s] 2024-02-21T22:11:02 <INF> [MQTT IF] Init
> [0d00h00m15s] 2024-02-21T22:11:02 <INF> [MQTT IF] Client started, waiting for established connection...
> [0d00h00m15s] 2024-02-21T22:11:02 <INF> [MAINCTRL] Starting Flow...
> [0d00h00m15s] 2024-02-21T22:11:02 <DBG> [MAINCTRL] ----------------------------------------------------------------
> [0d00h00m15s] 2024-02-21T22:11:02 <INF> [MAINCTRL] Round #1 started
> [0d00h00m15s] 2024-02-21T22:11:03 <DBG> [FLOWCTRL] Status: Take Image (22:11:03)
> [0d00h00m15s] 2024-02-21T22:11:03 <DBG> [MQTT IF] Published topic: watermeter/status, content: Take Image (msg_id=3)

> [0d00h00m15s] 2024-02-21T22:11:03 <DBG> [PSRAM] Init shared memory for step 'Take Image' (STBI buffers)
> [0d00h00m22s] 2024-02-21T22:11:09 <DBG> [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> [0d00h00m22s] 2024-02-21T22:11:09 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m22s] 2024-02-21T22:11:09 <DBG> [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> [0d00h00m22s] 2024-02-21T22:11:09 <DBG> [PSRAM] Allocating memory (307215 bytes) for STBI (use shared memory in PSRAM)...
> [0d00h00m22s] 2024-02-21T22:11:09 <DBG> [PSRAM] Allocating memory (153615 bytes) for STBI (use shared memory in PSRAM)...
> [0d00h00m22s] 2024-02-21T22:11:09 <DBG> [PSRAM] Allocating memory (153615 bytes) for STBI (use shared memory in PSRAM)...
> [0d00h00m22s] 2024-02-21T22:11:10 <DBG> [PSRAM] Allocated 643 bytes in PSRAM for 'STBI'
> [0d00h00m22s] 2024-02-21T22:11:10 <DBG> [PSRAM] Allocated 643 bytes in PSRAM for 'STBI'
> [0d00h00m22s] 2024-02-21T22:11:10 <DBG> [PSRAM] Allocated 643 bytes in PSRAM for 'STBI'
> [0d00h00m22s] 2024-02-21T22:11:10 <DBG> [PSRAM] Allocating memory (921601 bytes) for STBI (use shared memory in PSRAM)...
> [0d00h00m23s] 2024-02-21T22:11:10 <DBG> [PSRAM] Part of shared memory used for STBI (PSRAM, part of shared memory) is free again
> [0d00h00m23s] 2024-02-21T22:11:10 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m23s] 2024-02-21T22:11:10 <DBG> [PSRAM] Part of shared memory used for STBI (PSRAM, part of shared memory) is free again
> [0d00h00m23s] 2024-02-21T22:11:10 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m23s] 2024-02-21T22:11:10 <DBG> [PSRAM] Part of shared memory used for STBI (PSRAM, part of shared memory) is free again
> [0d00h00m23s] 2024-02-21T22:11:10 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m23s] 2024-02-21T22:11:10 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m25s] 2024-02-21T22:11:12 <DBG> [C IMG BASIS] Not freeing (zwImage as there was never PSRAM allocated for it)
> [0d00h00m25s] 2024-02-21T22:11:12 <DBG> [PSRAM] Deinit shared memory for step 'Take Image' (STBI buffers)
> [0d00h00m25s] 2024-02-21T22:11:12 <DBG> [FLOWCTRL] Status: Aligning (22:11:12)
> [0d00h00m25s] 2024-02-21T22:11:13 <DBG> [MQTT IF] Published topic: watermeter/status, content: Aligning (msg_id=4)
> [0d00h00m26s] 2024-02-21T22:11:13 <DBG> [PSRAM] Allocating tmpImage (921600 bytes, use shared memory in PSRAM)...
> [0d00h00m28s] 2024-02-21T22:11:15 <DBG> [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> [0d00h00m28s] 2024-02-21T22:11:15 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m28s] 2024-02-21T22:11:15 <DBG> [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> [0d00h00m28s] 2024-02-21T22:11:15 <DBG> [PSRAM] Allocated 3087 bytes in PSRAM for 'STBI'
> [0d00h00m28s] 2024-02-21T22:11:15 <DBG> [PSRAM] Allocated 783 bytes in PSRAM for 'STBI'
> [0d00h00m28s] 2024-02-21T22:11:15 <DBG> [PSRAM] Allocated 783 bytes in PSRAM for 'STBI'
> [0d00h00m28s] 2024-02-21T22:11:15 <DBG> [PSRAM] Allocated 63 bytes in PSRAM for 'STBI'
> [0d00h00m28s] 2024-02-21T22:11:15 <DBG> [PSRAM] Allocated 63 bytes in PSRAM for 'STBI'
> [0d00h00m28s] 2024-02-21T22:11:16 <DBG> [PSRAM] Allocated 63 bytes in PSRAM for 'STBI'
> [0d00h00m28s] 2024-02-21T22:11:16 <DBG> [PSRAM] Allocated 6661 bytes in PSRAM for 'STBI'
> [0d00h00m28s] 2024-02-21T22:11:16 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m28s] 2024-02-21T22:11:16 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m28s] 2024-02-21T22:11:16 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m28s] 2024-02-21T22:11:16 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m28s] 2024-02-21T22:11:16 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m28s] 2024-02-21T22:11:16 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m28s] 2024-02-21T22:11:16 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Allocated 3087 bytes in PSRAM for 'STBI'
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Allocated 783 bytes in PSRAM for 'STBI'
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Allocated 783 bytes in PSRAM for 'STBI'
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Allocated 61 bytes in PSRAM for 'STBI'
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Allocated 61 bytes in PSRAM for 'STBI'
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Allocated 61 bytes in PSRAM for 'STBI'
> [0d00h00m34s] 2024-02-21T22:11:22 <DBG> [PSRAM] Allocated 7135 bytes in PSRAM for 'STBI'
> [0d00h00m35s] 2024-02-21T22:11:22 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m35s] 2024-02-21T22:11:22 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m35s] 2024-02-21T22:11:22 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m35s] 2024-02-21T22:11:22 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m35s] 2024-02-21T22:11:22 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m35s] 2024-02-21T22:11:22 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m35s] 2024-02-21T22:11:22 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m41s] 2024-02-21T22:11:29 <DBG> [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> [0d00h00m48s] 2024-02-21T22:11:35 <DBG> [PSRAM] Shared memory used for tmpImage (PSRAM, part of shared memory) is free again
> [0d00h00m48s] 2024-02-21T22:11:36 <DBG> [FLOWCTRL] Status: Digitalization of ROIs (22:11:36)
> [0d00h00m48s] 2024-02-21T22:11:36 <DBG> [MQTT IF] Published topic: watermeter/status, content: Digitalization of ROIs (msg_id=5)
> [0d00h00m48s] 2024-02-21T22:11:36 <DBG> [CNN] doFlow after alignment
> [0d00h00m48s] 2024-02-21T22:11:36 <DBG> [PSRAM] Allocating Tensor Arena (819200 bytes, use shared memory in PSRAM)...
> [0d00h00m48s] 2024-02-21T22:11:36 <DBG> [TFLITE] CTfLiteClass::LoadModel
> [0d00h00m48s] 2024-02-21T22:11:36 <DBG> [TFLITE] CTfLiteClass::ReadFileToModel: /sdcard/config/dig-class100-0168_s2_q.tflite
> [0d00h00m48s] 2024-02-21T22:11:36 <DBG> [TFLITE] Loading Model /sdcard/config/dig-class100-0168_s2_q.tflite /size: 226968 bytes...
> [0d00h00m48s] 2024-02-21T22:11:36 <DBG> [PSRAM] Allocating Model memory (1363148 bytes, use shared memory in PSRAM)...
> [0d00h00m49s] 2024-02-21T22:11:36 <DBG> [TFLITE] CTfLiteClass::MakeAllocate
> [0d00h00m49s] 2024-02-21T22:11:36 <DBG> [CNN] Processing Number 'main'
> [0d00h00m49s] 2024-02-21T22:11:36 <DBG> [CNN] ROI #0 - TfLite
> [0d00h00m49s] 2024-02-21T22:11:36 <DBG> [CNN] CNN Type: Digital100 or Analogue100
> [0d00h00m49s] 2024-02-21T22:11:37 <DBG> [CNN] ROI #1 - TfLite
> [0d00h00m49s] 2024-02-21T22:11:37 <DBG> [CNN] CNN Type: Digital100 or Analogue100
> [0d00h00m50s] 2024-02-21T22:11:38 <DBG> [CNN] ROI #2 - TfLite
> [0d00h00m50s] 2024-02-21T22:11:38 <DBG> [CNN] CNN Type: Digital100 or Analogue100
> [0d00h00m51s] 2024-02-21T22:11:38 <DBG> [CNN] ROI #3 - TfLite
> [0d00h00m51s] 2024-02-21T22:11:38 <DBG> [CNN] CNN Type: Digital100 or Analogue100
> [0d00h00m51s] 2024-02-21T22:11:39 <DBG> [CNN] ROI #4 - TfLite
> [0d00h00m51s] 2024-02-21T22:11:39 <DBG> [CNN] CNN Type: Digital100 or Analogue100
> [0d00h00m52s] 2024-02-21T22:11:40 <DBG> [CNN] ROI #5 - TfLite
> [0d00h00m52s] 2024-02-21T22:11:40 <DBG> [CNN] CNN Type: Digital100 or Analogue100
> [0d00h00m53s] 2024-02-21T22:11:40 <DBG> [CNN] ROI #6 - TfLite
> [0d00h00m53s] 2024-02-21T22:11:40 <DBG> [CNN] CNN Type: Digital100 or Analogue100
> [0d00h00m53s] 2024-02-21T22:11:41 <DBG> [PSRAM] Shared memory used for Tensor Arena and model (PSRAM, part of shared memory) is free again
> [0d00h00m54s] 2024-02-21T22:11:41 <DBG> [FLOWCTRL] Status: Digitalization of ROIs (22:11:41)
> [0d00h00m54s] 2024-02-21T22:11:41 <DBG> [MQTT IF] Published topic: watermeter/status, content: Digitalization of ROIs (msg_id=6)
> [0d00h00m54s] 2024-02-21T22:11:41 <DBG> [CNN] doFlow after alignment
> [0d00h00m54s] 2024-02-21T22:11:41 <DBG> [PSRAM] Allocating Tensor Arena (819200 bytes, use shared memory in PSRAM)...
> [0d00h00m54s] 2024-02-21T22:11:41 <DBG> [TFLITE] CTfLiteClass::LoadModel
> [0d00h00m54s] 2024-02-21T22:11:41 <DBG> [TFLITE] CTfLiteClass::ReadFileToModel: /sdcard/config/ana-class100_0169_s1_q.tflite
> [0d00h00m54s] 2024-02-21T22:11:41 <DBG> [TFLITE] Loading Model /sdcard/config/ana-class100_0169_s1_q.tflite /size: 133784 bytes...
> [0d00h00m54s] 2024-02-21T22:11:42 <DBG> [PSRAM] Allocating Model memory (1363148 bytes, use shared memory in PSRAM)...
> [0d00h00m54s] 2024-02-21T22:11:42 <DBG> [TFLITE] CTfLiteClass::MakeAllocate
> [0d00h00m54s] 2024-02-21T22:11:42 <DBG> [CNN] Processing Number 'main'
> [0d00h00m54s] 2024-02-21T22:11:42 <DBG> [CNN] ROI #0 - TfLite
> [0d00h00m54s] 2024-02-21T22:11:42 <DBG> [CNN] CNN Type: Digital100 or Analogue100
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [PSRAM] Shared memory used for Tensor Arena and model (PSRAM, part of shared memory) is free again
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [FLOWCTRL] Status: Post-Processing (22:11:44)
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [MQTT IF] Published topic: watermeter/status, content: Post-Processing (msg_id=7)
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout _analog=0, _extendedResolution=0, prev=-1
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] PointerEvalAnalogNew - No predecessor - Result = 2 number: 2.200000 numeral_preceder = -1 Analog_error = 3
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout _analog=0, _extendedResolution=1, prev=2
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout(dig100-ext) result_before_decimal_point=5, result_after_decimal_point=3, prev=5
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 6 number: 5.900000 number_of_predecessors = 5.300000 eval_predecessors = 5 Digital_Uncertainty = 0.200000
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#PointerEvalHybridNew()= 6
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#result= 653
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 0 number: 0.000000 number_of_predecessors = 5.900000 eval_predecessors = 6 Digital_Uncertainty = 0.200000
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#PointerEvalHybridNew()= 0
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#result= 0653
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] PointerEvalHybridNew - NO analogue predecessor, zero crossing has taken placen = 2 number: 2.000000 number_of_predecessors = 0.000000 eval_predecessors = 0 Digital_Uncertainty = 0.200000
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#PointerEvalHybridNew()= 2
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#result= 20653
> [0d00h00m56s] 2024-02-21T22:11:44 <DBG> [CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 3 number: 3.000000 number_of_predecessors = 2.000000 eval_predecessors = 2 Digital_Uncertainty = 0.200000
> [0d00h00m57s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#PointerEvalHybridNew()= 3
> [0d00h00m57s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#result= 320653
> [0d00h00m57s] 2024-02-21T22:11:44 <DBG> [CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 0 number: 0.000000 number_of_predecessors = 3.000000 eval_predecessors = 3 Digital_Uncertainty = 0.200000
> [0d00h00m57s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#PointerEvalHybridNew()= 0
> [0d00h00m57s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#result= 0320653
> [0d00h00m57s] 2024-02-21T22:11:44 <DBG> [CNN] PointerEvalHybridNew - NO analogue predecessor, zero crossing has taken placen = 0 number: 0.000000 number_of_predecessors = 0.000000 eval_predecessors = 0 Digital_Uncertainty = 0.200000
> [0d00h00m57s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#PointerEvalHybridNew()= 0
> [0d00h00m57s] 2024-02-21T22:11:44 <DBG> [CNN] getReadout#result= 00320653
> [0d00h00m57s] 2024-02-21T22:11:44 <DBG> [POSTPROC] handleAllowNegativeRate for device: main
> [0d00h00m57s] 2024-02-21T22:11:44 <ERR> [POSTPROC] main: Raw: 0032.0652, Value: , Status: Rate too high - Read: 33.0652 - Pre: 32.0652 - Rate: 1.0000

**Comment by Duese123** [comment]
> Same issue with 15.6.0:
> 
> Previous Value: 32.06521 Raw Value: 0032.0652 Value Status: Rate too high - Read: 33.0652 - Pre: 32.0652 - Rate: 1.0000
> 
> Trace:
> 
> > [0d00h00m15s] 2024-02-21T22:11:02  [MQTT IF] Init
> > [0d00h00m15s] 2024-02-21T22:11:02  [MQTT IF] Client started, waiting for established connection...
> > [0d00h00m15s] 2024-02-21T22:11:02  [MAINCTRL] Starting Flow...
> > [0d00h00m15s] 2024-02-21T22:11:02  [MAINCTRL] ----------------------------------------------------------------
> > [0d00h00m15s] 2024-02-21T22:11:02  [MAINCTRL] Round #1 started
> > [0d00h00m15s] 2024-02-21T22:11:03  [FLOWCTRL] Status: Take Image (22:11:03)
> > [0d00h00m15s] 2024-02-21T22:11:03  [MQTT IF] Published topic: watermeter/status, content: Take Image (msg_id=3)
> 
> > [0d00h00m15s] 2024-02-21T22:11:03  [PSRAM] Init shared memory for step 'Take Image' (STBI buffers)
> > [0d00h00m22s] 2024-02-21T22:11:09  [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> > [0d00h00m22s] 2024-02-21T22:11:09  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m22s] 2024-02-21T22:11:09  [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> > [0d00h00m22s] 2024-02-21T22:11:09  [PSRAM] Allocating memory (307215 bytes) for STBI (use shared memory in PSRAM)...
> > [0d00h00m22s] 2024-02-21T22:11:09  [PSRAM] Allocating memory (153615 bytes) for STBI (use shared memory in PSRAM)...
> > [0d00h00m22s] 2024-02-21T22:11:09  [PSRAM] Allocating memory (153615 bytes) for STBI (use shared memory in PSRAM)...
> > [0d00h00m22s] 2024-02-21T22:11:10  [PSRAM] Allocated 643 bytes in PSRAM for 'STBI'
> > [0d00h00m22s] 2024-02-21T22:11:10  [PSRAM] Allocated 643 bytes in PSRAM for 'STBI'
> > [0d00h00m22s] 2024-02-21T22:11:10  [PSRAM] Allocated 643 bytes in PSRAM for 'STBI'
> > [0d00h00m22s] 2024-02-21T22:11:10  [PSRAM] Allocating memory (921601 bytes) for STBI (use shared memory in PSRAM)...
> > [0d00h00m23s] 2024-02-21T22:11:10  [PSRAM] Part of shared memory used for STBI (PSRAM, part of shared memory) is free again
> > [0d00h00m23s] 2024-02-21T22:11:10  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m23s] 2024-02-21T22:11:10  [PSRAM] Part of shared memory used for STBI (PSRAM, part of shared memory) is free again
> > [0d00h00m23s] 2024-02-21T22:11:10  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m23s] 2024-02-21T22:11:10  [PSRAM] Part of shared memory used for STBI (PSRAM, part of shared memory) is free again
> > [0d00h00m23s] 2024-02-21T22:11:10  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m23s] 2024-02-21T22:11:10  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m25s] 2024-02-21T22:11:12  [C IMG BASIS] Not freeing (zwImage as there was never PSRAM allocated for it)
> > [0d00h00m25s] 2024-02-21T22:11:12  [PSRAM] Deinit shared memory for step 'Take Image' (STBI buffers)
> > [0d00h00m25s] 2024-02-21T22:11:12  [FLOWCTRL] Status: Aligning (22:11:12)
> > [0d00h00m25s] 2024-02-21T22:11:13  [MQTT IF] Published topic: watermeter/status, content: Aligning (msg_id=4)
> > [0d00h00m26s] 2024-02-21T22:11:13  [PSRAM] Allocating tmpImage (921600 bytes, use shared memory in PSRAM)...
> > [0d00h00m28s] 2024-02-21T22:11:15  [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> > [0d00h00m28s] 2024-02-21T22:11:15  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m28s] 2024-02-21T22:11:15  [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> > [0d00h00m28s] 2024-02-21T22:11:15  [PSRAM] Allocated 3087 bytes in PSRAM for 'STBI'
> > [0d00h00m28s] 2024-02-21T22:11:15  [PSRAM] Allocated 783 bytes in PSRAM for 'STBI'
> > [0d00h00m28s] 2024-02-21T22:11:15  [PSRAM] Allocated 783 bytes in PSRAM for 'STBI'
> > [0d00h00m28s] 2024-02-21T22:11:15  [PSRAM] Allocated 63 bytes in PSRAM for 'STBI'
> > [0d00h00m28s] 2024-02-21T22:11:15  [PSRAM] Allocated 63 bytes in PSRAM for 'STBI'
> > [0d00h00m28s] 2024-02-21T22:11:16  [PSRAM] Allocated 63 bytes in PSRAM for 'STBI'
> > [0d00h00m28s] 2024-02-21T22:11:16  [PSRAM] Allocated 6661 bytes in PSRAM for 'STBI'
> > [0d00h00m28s] 2024-02-21T22:11:16  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m28s] 2024-02-21T22:11:16  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m28s] 2024-02-21T22:11:16  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m28s] 2024-02-21T22:11:16  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m28s] 2024-02-21T22:11:16  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m28s] 2024-02-21T22:11:16  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m28s] 2024-02-21T22:11:16  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Allocated 18456 bytes in PSRAM for 'STBI'
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Allocated 3087 bytes in PSRAM for 'STBI'
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Allocated 783 bytes in PSRAM for 'STBI'
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Allocated 783 bytes in PSRAM for 'STBI'
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Allocated 61 bytes in PSRAM for 'STBI'
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Allocated 61 bytes in PSRAM for 'STBI'
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Allocated 61 bytes in PSRAM for 'STBI'
> > [0d00h00m34s] 2024-02-21T22:11:22  [PSRAM] Allocated 7135 bytes in PSRAM for 'STBI'
> > [0d00h00m35s] 2024-02-21T22:11:22  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m35s] 2024-02-21T22:11:22  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m35s] 2024-02-21T22:11:22  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m35s] 2024-02-21T22:11:22  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m35s] 2024-02-21T22:11:22  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m35s] 2024-02-21T22:11:22  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m35s] 2024-02-21T22:11:22  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m41s] 2024-02-21T22:11:29  [PSRAM] Freeing memory in PSRAM used for 'STBI'...
> > [0d00h00m48s] 2024-02-21T22:11:35  [PSRAM] Shared memory used for tmpImage (PSRAM, part of shared memory) is free again
> > [0d00h00m48s] 2024-02-21T22:11:36  [FLOWCTRL] Status: Digitalization of ROIs (22:11:36)
> > [0d00h00m48s] 2024-02-21T22:11:36  [MQTT IF] Published topic: watermeter/status, content: Digitalization of ROIs (msg_id=5)
> > [0d00h00m48s] 2024-02-21T22:11:36  [CNN] doFlow after alignment
> > [0d00h00m48s] 2024-02-21T22:11:36  [PSRAM] Allocating Tensor Arena (819200 bytes, use shared memory in PSRAM)...
> > [0d00h00m48s] 2024-02-21T22:11:36  [TFLITE] CTfLiteClass::LoadModel
> > [0d00h00m48s] 2024-02-21T22:11:36  [TFLITE] CTfLiteClass::ReadFileToModel: /sdcard/config/dig-class100-0168_s2_q.tflite
> > [0d00h00m48s] 2024-02-21T22:11:36  [TFLITE] Loading Model /sdcard/config/dig-class100-0168_s2_q.tflite /size: 226968 bytes...
> > [0d00h00m48s] 2024-02-21T22:11:36  [PSRAM] Allocating Model memory (1363148 bytes, use shared memory in PSRAM)...
> > [0d00h00m49s] 2024-02-21T22:11:36  [TFLITE] CTfLiteClass::MakeAllocate
> > [0d00h00m49s] 2024-02-21T22:11:36  [CNN] Processing Number 'main'
> > [0d00h00m49s] 2024-02-21T22:11:36  [CNN] ROI #0 - TfLite
> > [0d00h00m49s] 2024-02-21T22:11:36  [CNN] CNN Type: Digital100 or Analogue100
> > [0d00h00m49s] 2024-02-21T22:11:37  [CNN] ROI #1 - TfLite
> > [0d00h00m49s] 2024-02-21T22:11:37  [CNN] CNN Type: Digital100 or Analogue100
> > [0d00h00m50s] 2024-02-21T22:11:38  [CNN] ROI #2 - TfLite
> > [0d00h00m50s] 2024-02-21T22:11:38  [CNN] CNN Type: Digital100 or Analogue100
> > [0d00h00m51s] 2024-02-21T22:11:38  [CNN] ROI #3 - TfLite
> > [0d00h00m51s] 2024-02-21T22:11:38  [CNN] CNN Type: Digital100 or Analogue100
> > [0d00h00m51s] 2024-02-21T22:11:39  [CNN] ROI #4 - TfLite
> > [0d00h00m51s] 2024-02-21T22:11:39  [CNN] CNN Type: Digital100 or Analogue100
> > [0d00h00m52s] 2024-02-21T22:11:40  [CNN] ROI #5 - TfLite
> > [0d00h00m52s] 2024-02-21T22:11:40  [CNN] CNN Type: Digital100 or Analogue100
> > [0d00h00m53s] 2024-02-21T22:11:40  [CNN] ROI #6 - TfLite
> > [0d00h00m53s] 2024-02-21T22:11:40  [CNN] CNN Type: Digital100 or Analogue100
> > [0d00h00m53s] 2024-02-21T22:11:41  [PSRAM] Shared memory used for Tensor Arena and model (PSRAM, part of shared memory) is free again
> > [0d00h00m54s] 2024-02-21T22:11:41  [FLOWCTRL] Status: Digitalization of ROIs (22:11:41)
> > [0d00h00m54s] 2024-02-21T22:11:41  [MQTT IF] Published topic: watermeter/status, content: Digitalization of ROIs (msg_id=6)
> > [0d00h00m54s] 2024-02-21T22:11:41  [CNN] doFlow after alignment
> > [0d00h00m54s] 2024-02-21T22:11:41  [PSRAM] Allocating Tensor Arena (819200 bytes, use shared memory in PSRAM)...
> > [0d00h00m54s] 2024-02-21T22:11:41  [TFLITE] CTfLiteClass::LoadModel
> > [0d00h00m54s] 2024-02-21T22:11:41  [TFLITE] CTfLiteClass::ReadFileToModel: /sdcard/config/ana-class100_0169_s1_q.tflite
> > [0d00h00m54s] 2024-02-21T22:11:41  [TFLITE] Loading Model /sdcard/config/ana-class100_0169_s1_q.tflite /size: 133784 bytes...
> > [0d00h00m54s] 2024-02-21T22:11:42  [PSRAM] Allocating Model memory (1363148 bytes, use shared memory in PSRAM)...
> > [0d00h00m54s] 2024-02-21T22:11:42  [TFLITE] CTfLiteClass::MakeAllocate
> > [0d00h00m54s] 2024-02-21T22:11:42  [CNN] Processing Number 'main'
> > [0d00h00m54s] 2024-02-21T22:11:42  [CNN] ROI #0 - TfLite
> > [0d00h00m54s] 2024-02-21T22:11:42  [CNN] CNN Type: Digital100 or Analogue100
> > [0d00h00m56s] 2024-02-21T22:11:44  [PSRAM] Shared memory used for Tensor Arena and model (PSRAM, part of shared memory) is free again
> > [0d00h00m56s] 2024-02-21T22:11:44  [FLOWCTRL] Status: Post-Processing (22:11:44)
> > [0d00h00m56s] 2024-02-21T22:11:44  [MQTT IF] Published topic: watermeter/status, content: Post-Processing (msg_id=7)
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] getReadout _analog=0, _extendedResolution=0, prev=-1
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] PointerEvalAnalogNew - No predecessor - Result = 2 number: 2.200000 numeral_preceder = -1 Analog_error = 3
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] getReadout _analog=0, _extendedResolution=1, prev=2
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] getReadout(dig100-ext) result_before_decimal_point=5, result_after_decimal_point=3, prev=5
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 6 number: 5.900000 number_of_predecessors = 5.300000 eval_predecessors = 5 Digital_Uncertainty = 0.200000
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] getReadout#PointerEvalHybridNew()= 6
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] getReadout#result= 653
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 0 number: 0.000000 number_of_predecessors = 5.900000 eval_predecessors = 6 Digital_Uncertainty = 0.200000
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] getReadout#PointerEvalHybridNew()= 0
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] getReadout#result= 0653
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] PointerEvalHybridNew - NO analogue predecessor, zero crossing has taken placen = 2 number: 2.000000 number_of_predecessors = 0.000000 eval_predecessors = 0 Digital_Uncertainty = 0.200000
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] getReadout#PointerEvalHybridNew()= 2
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] getReadout#result= 20653
> > [0d00h00m56s] 2024-02-21T22:11:44  [CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 3 number: 3.000000 number_of_predecessors = 2.000000 eval_predecessors = 2 Digital_Uncertainty = 0.200000
> > [0d00h00m57s] 2024-02-21T22:11:44  [CNN] getReadout#PointerEvalHybridNew()= 3
> > [0d00h00m57s] 2024-02-21T22:11:44  [CNN] getReadout#result= 320653
> > [0d00h00m57s] 2024-02-21T22:11:44  [CNN] PointerEvalHybridNew - NO analogue predecessor, no change of digits, as pre-decimal point far enough away = 0 number: 0.000000 number_of_predecessors = 3.000000 eval_predecessors = 3 Digital_Uncertainty = 0.200000
> > [0d00h00m57s] 2024-02-21T22:11:44  [CNN] getReadout#PointerEvalHybridNew()= 0
> > [0d00h00m57s] 2024-02-21T22:11:44  [CNN] getReadout#result= 0320653
> > [0d00h00m57s] 2024-02-21T22:11:44  [CNN] PointerEvalHybridNew - NO analogue predecessor, zero crossing has taken placen = 0 number: 0.000000 number_of_predecessors = 0.000000 eval_predecessors = 0 Digital_Uncertainty = 0.200000
> > [0d00h00m57s] 2024-02-21T22:11:44  [CNN] getReadout#PointerEvalHybridNew()= 0
> > [0d00h00m57s] 2024-02-21T22:11:44  [CNN] getReadout#result= 00320653
> > [0d00h00m57s] 2024-02-21T22:11:44  [POSTPROC] handleAllowNegativeRate for device: main
> > [0d00h00m57s] 2024-02-21T22:11:44  [POSTPROC] main: Raw: 0032.0652, Value: , Status: Rate too high - Read: 33.0652 - Pre: 32.0652 - Rate: 1.0000

Flash to 15.4 or 15.7

**Comment by eikejung** [comment]
Same issue here. I‘m on 15.7. Every time the last digit turns, I get „rate too high“. Tried nearly every combonation. At the moment the parameter is 6.0, but without any effect. Error begins at x.680.

**Comment by pos-ei-don** [comment]
[eikejung](https://github.com/eikejung) , please open your own issue.
My problem is fiex for me!
