### ISSUE TITLE
Home Assistant state class and unit of measure

### ISSUE THREAD

**Issue by ykri** [jomjol/AI-on-the-edge-device#3331]
### Issue

Since last HA update 2024.10 I am getting two repair issues for raw value. 
```

The entity no longer has a state class

We have generated statistics for 'ElectrMeter Raw Value' (sensor.electrmeter_raw) in the past, but it no longer has a state class, therefore, we cannot track long term statistics for it anymore.

Statistics cannot be generated until this entity has a supported state class.
If the state class was previously provided by an integration, this might be a bug. Please report an issue.
If you previously set the state class yourself, please correct it. [The different state classes and when to use which can be found in the developer documentation.](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)
If the state class has permanently been removed, you may want to delete the long term statistics of it from your database.
Do you want to permanently delete the long term statistics of sensor.electrmeter_raw from your database?

```
 and

```

The unit has changed

The unit of 'ElectrMeter Raw Value' (sensor.electrmeter_raw) changed to '' which can't be converted to the previously stored unit, 'kWh'.
If the historic statistic values have a wrong unit, you can update the units of the old values. The values will not be updated.
Otherwise you can choose to delete all historic statistic values, and start over

```

**Comment by caco3** [comment]
I updated the HA Discover topics in https://github.com/jomjol/AI-on-the-edge-device/pull/3332
This should fix the first issue. I think the 2nd issue is just a follow-up error due to the first error.

I can't test it myself since I don't see this error. So I need you to test and confirm it is ok now!
Please test the latest (most top) build from https://github.com/jomjol/AI-on-the-edge-device/actions?query=branch%3Asupport-homeassistant-2024.10

**Comment by ykri** [comment]
Still the same. See the HA MQTT debug info for raw

![image](https://github.com/user-attachments/assets/dafcc3e9-0f32-45e9-b511-7f448bb8b1e7)

**Comment by caco3** [comment]
I can not reproduce this!
For me it looks ok now:
![grafik](https://github.com/user-attachments/assets/21e4a3b1-ad41-43cb-b836-281d2298aa6c)

Maybe try to delete the discovery topics and let the device re-send them.

**Comment by ykri** [comment]
I tried to delete the discovery topics using MQTT Explorer but I am back to zero. Is there any other clever way to do this discovery topics deletion?

**Comment by caco3** [comment]
Did you really use a build from https://github.com/jomjol/AI-on-the-edge-device/actions/workflows/build.yaml?query=branch%3Asupport-homeassistant-2024.10?
Looking on your screenshot I see that you are not running the right firmware!

If it still does not work:
You can also delete the device in HA. It will show up again after the next sending of the discovery topics.

**Comment by ykri** [comment]
I guess so. I updated again using the latest here ![image](https://github.com/user-attachments/assets/0da3ee1f-224a-4c55-836a-56d986c8f311)

and this is from MQTT Explorer the post for Raw after the update. You can see that it is the same commit from development branch main ![image](https://github.com/user-attachments/assets/51274a84-deb8-4c47-bf63-73db046302ee)

And here is from HA

![image](https://github.com/user-attachments/assets/550ec59b-4531-4077-ae9b-c323885b4ea8)

There must be something I am doing wrong but what?  

Thanks for your patience!

**Comment by caco3** [comment]
You again did not use the link I showed you!
you need the latest build of the branch "support-homeassistant-2024.10, but you used "main"!

**Comment by ykri** [comment]
I owe you a thousand apologies. It worked. As you said it I was using the wrong update. 

Thanks!!!
